title: spffld0's blog
email: spffld0@outlook.com
description: A blog on math and competitive programming
baseurl: ""
url: ""
permalink: pretty


# Build settings
theme: just-the-docs

# Syntax highlighting with line numbers
compress_html:
  ignore:
    envs: all

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

back_to_top: true
back_to_top_text: "Back to top"


# Callout configuration
callouts_level: quiet 
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red